/**
 * @param {string} letter
 * @param {number} dots
 *
 * Class representing a Minecraft character
 *
 * The length of the letter is represented by "dots"
 */
class MinecraftChar {
  private _char: string;
  private _dots: number;

  constructor(char: string, dots: number) {
    this._char = char;
    this._dots = dots;
  }

  set letter(letter: string) {
    this._char = letter;
  }

  get letter() {
    return this._char;
  }

  set dots(dots: number) {
    this._dots = dots;
  }

  get dots() {
    return this._dots;
  }
}

/**
 * Returns a list minecraft characters and the amount of "dots" they take up on a page
 * @returns An array of Char objects, containing character and dots
 */
function getChars() {
  return [
    new MinecraftChar('À', 6),
    new MinecraftChar('Á', 6),
    new MinecraftChar('Â', 6),
    new MinecraftChar('È', 6),
    new MinecraftChar('Ê', 6),
    new MinecraftChar('Ë', 6),
    new MinecraftChar('Í', 4),
    new MinecraftChar('Ó', 6),
    new MinecraftChar('Ô', 6),
    new MinecraftChar('Õ', 6),
    new MinecraftChar('Ú', 6),
    new MinecraftChar('ß', 6),
    new MinecraftChar('ã', 6),
    new MinecraftChar('õ', 6),
    new MinecraftChar('ğ', 6),
    new MinecraftChar('İ', 4),
    new MinecraftChar('ı', 4),
    new MinecraftChar('Œ', 6),
    new MinecraftChar('œ', 7),
    new MinecraftChar('Ş', 6),
    new MinecraftChar('ş', 6),
    new MinecraftChar('Ŵ', 6),
    new MinecraftChar('ŵ', 6),
    new MinecraftChar('ž', 6),
    new MinecraftChar('ȇ', 6),
    new MinecraftChar('!', 2),
    new MinecraftChar('"', 5),
    new MinecraftChar('#', 6),
    new MinecraftChar('$', 6),
    new MinecraftChar('%', 6),
    new MinecraftChar('&', 6),
    new MinecraftChar("'", 3),
    new MinecraftChar('(', 5),
    new MinecraftChar(')', 5),
    new MinecraftChar('*', 5),
    new MinecraftChar('+', 6),
    new MinecraftChar(',', 2),
    new MinecraftChar('-', 6),
    new MinecraftChar('.', 2),
    new MinecraftChar('/', 6),
    new MinecraftChar('0', 6),
    new MinecraftChar('1', 6),
    new MinecraftChar('2', 6),
    new MinecraftChar('3', 6),
    new MinecraftChar('4', 6),
    new MinecraftChar('5', 6),
    new MinecraftChar('6', 6),
    new MinecraftChar('7', 6),
    new MinecraftChar('8', 6),
    new MinecraftChar('9', 6),
    new MinecraftChar(':', 2),
    new MinecraftChar(';', 2),
    new MinecraftChar('<', 5),
    new MinecraftChar('=', 6),
    new MinecraftChar('>', 5),
    new MinecraftChar('?', 6),
    new MinecraftChar('@', 7),
    new MinecraftChar('A', 6),
    new MinecraftChar('B', 6),
    new MinecraftChar('C', 6),
    new MinecraftChar('D', 6),
    new MinecraftChar('E', 6),
    new MinecraftChar('F', 6),
    new MinecraftChar('G', 6),
    new MinecraftChar('H', 6),
    new MinecraftChar('I', 4),
    new MinecraftChar('J', 6),
    new MinecraftChar('K', 6),
    new MinecraftChar('L', 6),
    new MinecraftChar('M', 6),
    new MinecraftChar('N', 6),
    new MinecraftChar('O', 6),
    new MinecraftChar('P', 6),
    new MinecraftChar('Q', 6),
    new MinecraftChar('R', 6),
    new MinecraftChar('S', 6),
    new MinecraftChar('T', 6),
    new MinecraftChar('U', 6),
    new MinecraftChar('V', 6),
    new MinecraftChar('W', 6),
    new MinecraftChar('X', 6),
    new MinecraftChar('Y', 6),
    new MinecraftChar('Z', 6),
    new MinecraftChar('[', 4),
    new MinecraftChar(']', 4),
    new MinecraftChar('^', 6),
    new MinecraftChar('_', 6),
    new MinecraftChar('`', 3),
    new MinecraftChar('a', 6),
    new MinecraftChar('b', 6),
    new MinecraftChar('c', 6),
    new MinecraftChar('d', 6),
    new MinecraftChar('e', 6),
    new MinecraftChar('f', 5),
    new MinecraftChar('g', 6),
    new MinecraftChar('h', 6),
    new MinecraftChar('i', 2),
    new MinecraftChar('j', 6),
    new MinecraftChar('k', 5),
    new MinecraftChar('l', 3),
    new MinecraftChar('m', 6),
    new MinecraftChar('n', 6),
    new MinecraftChar('o', 6),
    new MinecraftChar('p', 6),
    new MinecraftChar('q', 6),
    new MinecraftChar('r', 6),
    new MinecraftChar('s', 6),
    new MinecraftChar('t', 4),
    new MinecraftChar('u', 6),
    new MinecraftChar('v', 6),
    new MinecraftChar('w', 6),
    new MinecraftChar('x', 6),
    new MinecraftChar('y', 6),
    new MinecraftChar('z', 6),
    new MinecraftChar('‘', 3),
    new MinecraftChar('’', 3),
    new MinecraftChar('{', 5),
    new MinecraftChar('|', 2),
    new MinecraftChar('}', 5),
    new MinecraftChar('~', 7),
    new MinecraftChar('–', 7),
    new MinecraftChar('Ç', 6),
    new MinecraftChar('ü', 6),
    new MinecraftChar('é', 6),
    new MinecraftChar('â', 6),
    new MinecraftChar('ä', 6),
    new MinecraftChar('à', 6),
    new MinecraftChar('å', 6),
    new MinecraftChar('ç', 6),
    new MinecraftChar('ê', 6),
    new MinecraftChar('ë', 6),
    new MinecraftChar('è', 6),
    new MinecraftChar('ï', 4),
    new MinecraftChar('î', 6),
    new MinecraftChar('ì', 3),
    new MinecraftChar('Ä', 6),
    new MinecraftChar('Å', 6),
    new MinecraftChar('É', 6),
    new MinecraftChar('æ', 6),
    new MinecraftChar('Æ', 6),
    new MinecraftChar('ô', 6),
    new MinecraftChar('ö', 6),
    new MinecraftChar('ò', 6),
    new MinecraftChar('û', 6),
    new MinecraftChar('ù', 6),
    new MinecraftChar('ÿ', 6),
    new MinecraftChar('Ö', 6),
    new MinecraftChar('Ü', 6),
    new MinecraftChar('ø', 6),
    new MinecraftChar('£', 6),
    new MinecraftChar('Ø', 6),
    new MinecraftChar('×', 4),
    new MinecraftChar('ƒ', 6),
    new MinecraftChar('á', 6),
    new MinecraftChar('í', 3),
    new MinecraftChar('ó', 6),
    new MinecraftChar('ú', 6),
    new MinecraftChar('ñ', 6),
    new MinecraftChar('Ñ', 6),
    new MinecraftChar('ª', 6),
    new MinecraftChar('º', 6),
    new MinecraftChar('¿', 6),
    new MinecraftChar('®', 7),
    new MinecraftChar('¬', 6),
    new MinecraftChar('½', 6),
    new MinecraftChar('¼', 6),
    new MinecraftChar('¡', 2),
    new MinecraftChar('«', 6),
    new MinecraftChar('»', 6),
    new MinecraftChar('░', 8),
    new MinecraftChar('▒', 9),
    new MinecraftChar('▓', 9),
    new MinecraftChar('│', 6),
    new MinecraftChar('┤', 6),
    new MinecraftChar('╡', 6),
    new MinecraftChar('╢', 8),
    new MinecraftChar('╖', 8),
    new MinecraftChar('╕', 6),
    new MinecraftChar('╣', 8),
    new MinecraftChar('║', 8),
    new MinecraftChar('╗', 8),
    new MinecraftChar('╝', 8),
    new MinecraftChar('╜', 8),
    new MinecraftChar('╛', 6),
    new MinecraftChar('┐', 6),
    new MinecraftChar('└', 9),
    new MinecraftChar('┴', 9),
    new MinecraftChar('┬', 9),
    new MinecraftChar('├', 9),
    new MinecraftChar('─', 9),
    new MinecraftChar('┼', 9),
    new MinecraftChar('╞', 9),
    new MinecraftChar('╟', 9),
    new MinecraftChar('╚', 9),
    new MinecraftChar('╔', 9),
    new MinecraftChar('╩', 9),
    new MinecraftChar('╦', 9),
    new MinecraftChar('╠', 9),
    new MinecraftChar('═', 9),
    new MinecraftChar('╬', 9),
    new MinecraftChar('╧', 9),
    new MinecraftChar('╨', 9),
    new MinecraftChar('╤', 9),
    new MinecraftChar('╥', 9),
    new MinecraftChar('╙', 9),
    new MinecraftChar('╘', 9),
    new MinecraftChar('╒', 9),
    new MinecraftChar('╓', 9),
    new MinecraftChar('╫', 9),
    new MinecraftChar('╪', 9),
    new MinecraftChar('┘', 6),
    new MinecraftChar('┌', 9),
    new MinecraftChar('█', 9),
    new MinecraftChar('▄', 9),
    new MinecraftChar('▌', 5),
    new MinecraftChar('▐', 9),
    new MinecraftChar('▀', 9),
    new MinecraftChar('α', 8),
    new MinecraftChar('β', 7),
    new MinecraftChar('Γ', 7),
    new MinecraftChar('π', 8),
    new MinecraftChar('Σ', 7),
    new MinecraftChar('σ', 8),
    new MinecraftChar('μ', 8),
    new MinecraftChar('τ', 8),
    new MinecraftChar('Φ', 7),
    new MinecraftChar('Θ', 8),
    new MinecraftChar('Ω', 8),
    new MinecraftChar('δ', 7),
    new MinecraftChar('∞', 9),
    new MinecraftChar('∅', 9),
    new MinecraftChar('∈', 6),
    new MinecraftChar('∩', 7),
    new MinecraftChar('≡', 7),
    new MinecraftChar('±', 7),
    new MinecraftChar('≥', 7),
    new MinecraftChar('≤', 7),
    new MinecraftChar('⌠', 9),
    new MinecraftChar('⌡', 6),
    new MinecraftChar('÷', 7),
    new MinecraftChar('≈', 8),
    new MinecraftChar('°', 7),
    new MinecraftChar('∙', 6),
    new MinecraftChar('·', 6),
    new MinecraftChar('√', 9),
    new MinecraftChar('ⁿ', 7),
    new MinecraftChar('²', 6),
    new MinecraftChar('■', 7),
    new MinecraftChar(' ', 4),
    new MinecraftChar('\n', 0),
  ];
}

export default getChars;
